#jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://111.230.46.50:3306/mysql?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#jdbc.username=root
#jdbc.password=@#45672gd

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://111.230.46.50:3306/mysql?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: 'root'
    password: '@#45672gd'
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092

kafka:
  topic:
    test-topic: 'test1'

